---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./route.yaml
  - ./securitypolicy.yaml
  - ./service.yaml
  - ./statefulset.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: rethink-config-tpl
    files:
      - config.json=./config/config.json
generatorOptions:
  disableNameSuffixHash: true
