apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: internal
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    "homelab/gateway-type": internal
spec:
  gatewayClassName: internal
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: internal
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              internal-gateway-access: "true"
    - name: unifi-passthrough
      protocol: TLS
      port: 443
      hostname: "unifi.internal.${SECRET_DOMAIN}"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              internal-gateway-access: "true"
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.internal.${SECRET_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: internal-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              internal-gateway-access: "true"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authelia-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    selector:
      matchExpressions:
        - key: auth
          operator: In
          values:
            - "authelia"
        # - key: auth
        #   operator: NotIn
        #   values:
        #     - "self-managed"
  extAuth:
    headersToExtAuth:
      - 'accept'
      - 'cookie'
      - 'authorization'
      - 'header-authorization'
      - 'x-forwarded-proto'
    failOpen: false
    http:
      backendRefs:
        - name: 'authelia'
          namespace: 'security'
          port: 80
      path: '/api/authz/ext-authz/'
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email
