---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: garage-secret
    creationPolicy: Owner
    template:
      data:
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET }}"
        GARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: garage
