---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.17.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: snapshot-controller
      namespace: volsync-system
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    toolbox:
      enabled: true

    cephClusterSpec:
      # https://rook.io/docs/rook/v1.10/Storage-Configuration/Advanced/ceph-configuration/#custom-cephconf-settings
      cephConfig:
        global:
          bdev_enable_discard: "true" # quote
          bdev_async_discard_threads: "1" # quote
          osd_class_update_on_start: "false" # quote
          device_failure_prediction_mode: local # requires mgr module
          osd_pool_default_size: "3" # quote
          osd_pool_default_min_size: "2" #quote
      mgr:
        count: &node-count 3
        modules:
          - name: diskprediction_local
            enabled: true
          - name: insights
            enabled: true
          - name: pg_autoscaler
            enabled: true
          - name: rook
            enabled: true
      mon:
        count: *node-count
      network:
        provider: host
        connections:
          requireMsgr2: true
      resources:
        mgr:
          requests:
            memory: 512Mi
            cpu: 0m
          limits:
            memory: 2Gi
        mon:
          requests:
            memory: 512Mi
            cpu: 0m
          limits:
            memory: 4Gi
        prepareosd:
          requests:
            memory: 50Mi
            cpu: 0m
        osd:
          requests:
            memory: 2Gi
            cpu: 0m
          limits:
            memory: 6Gi
        mgr-sidecar:
          requests:
            memory: 128Mi
            cpu: 0m
          limits:
            memory: 256Mi
        crashcollector:
          requests:
            memory: 60Mi
            cpu: 0m
          limits:
            memory: 60Mi
        logcollector:
          requests:
            memory: 100Mi
            cpu: 0m
          limits:
            memory: 1Gi
        cleanup:
          requests:
            memory: 100Mi
            cpu: 0m
          limits:
            memory: 1Gi
        exporter:
          requests:
            memory: 50Mi
            cpu: 0m
          limits:
            memory: 128Mi
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
        # prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090
      storage:
        useAllNodes: true
        useAllDevices: true
        deviceFilter: nvme0n1
        config:
          osdsPerDevice: "1"
      placement:
        mgr: &placement
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
        mon: *placement
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: *node-count
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: false
      deletionPolicy: Delete
    cephFileSystems:
      - name: &cephFileSystemName ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: *node-count
          dataPools:
            - failureDomain: host
              replicated:
                size: *node-count
              name: data0
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                memory: 1Gi
                cpu: 0m
              limits:
                memory: 4Gi
            placement:
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: kubernetes.io/hostname
                  whenUnsatisfiable: DoNotSchedule
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: ceph-mds
                      app.kubernetes.io/part-of: *cephFileSystemName
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystemVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-filesystem
      isDefault: false
      deletionPolicy: Delete
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: *node-count
          dataPool:
            failureDomain: host
            # erasureCoded: # Use this once we have 3 nodes
            #   dataChunks: 2
            #   codingChunks: 1
            replicated:
              size: *node-count
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              requests:
                memory: 1Gi
                cpu: 0m
              limits:
                memory: 2Gi
            instances: 2
            priorityClassName: system-cluster-critical
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          parameters:
            region: us-east-1
