apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-dashboard
spec:
  hostnames:
    - "rook.internal.${SECRET_DOMAIN}"
  parentRefs:
    - name: internal
      namespace: network
  rules:
    - backendRefs:
        - kind: Service
          name: rook-ceph-mgr-dashboard
          port: 7000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-rgw
spec:
  hostnames:
    - "rgw.internal.${SECRET_DOMAIN}"
  parentRefs:
    - name: internal
      namespace: network
  rules:
    - backendRefs:
        - kind: Service
          name: rook-ceph-rgw-ceph-objectstore
          port: 80
