---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # The TunnelSecret value here is gotten by base64 decoding the token that you get from the cloudflare UI
        # it will be json and have 3 values matching the 3 below here.
        credentials.json: |
          {
            "AccountTag": "{{ index . "CLOUDFLARE_TUNNEL_TAG" }}",
            "TunnelSecret": "{{ index . "CLOUDFLARE_TUNNEL_SECRET" }}",
            "TunnelID": "{{ index . "CLOUDFLARE_TUNNEL_ID" }}"
          }
  dataFrom:
    - extract:
        key: cloudflare-tunnel
