---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dynamic-hass-configs
spec:
  interval: 30m
  chart:
    spec:
      chart: dynamic/dynamic-hass-configs
      version: v0.1.0
      sourceRef:
        kind: GitRepository
        name: hass-configs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: homelab-data-zigbee-devices
