---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: cloudflare-tunnel
        property: CLOUDFLARE_TUNNEL_ID
