apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: gateway-external
        type: LoadBalancer
        loadBalancerIP: 192.168.254.3
