apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deploy-key-hass-configs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: deploy-key-hass-configs
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: deploy_key_hass_configs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hass-configs
spec:
  interval: 5m0s
  provider: generic
  url: ssh://git@github.com/nickdavies/hass-configs.git
  ref:
    branch: kubernetes
  secretRef:
    name: deploy-key-hass-configs
