---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: gateway-ip-pool
spec:
  avoidBuggyIPs: true
  addresses:
  - 192.168.254.2-192.168.254.4
  serviceAllocation:
    priority: 0
    namespaces:
      - network
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
spec:
  avoidBuggyIPs: true
  addresses:
  - 192.168.254.100-192.168.254.199
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-pool
spec:
  avoidBuggyIPs: true
  addresses:
  - 192.168.254.200-192.168.254.254
  autoAssign: false
