---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app internal-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: internal-dns-secret
            key: api-token
    extraArgs:
      - --gateway-namespace=network
      - --gateway-label-filter=homelab/gateway-type=internal
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    logLevel: debug
    policy: sync
    sources:
     - gateway-httproute
     - gateway-tlsroute
     - gateway-tcproute
     - gateway-udproute
     - crd
    txtPrefix: k8s.
    txtOwnerId: kubernetes-home-internal
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "*.${SECRET_DOMAIN}"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: internal-dns-secret
