---
machine:
  install:
    diskSelector:
      serial: "0x87c3c193"
  kubelet:
    extraConfig:
      registerNode: true
      registerWithTaints:
        - effect: NoSchedule
          key: homelab/special-node
          value: laundry-pi
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: k8s-node-4
