---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
  dataFrom:
    - extract:
        key: immich
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-config
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-config-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "backup": {
              "database": {
                "cronExpression": "0 02 * * *",
                "enabled": true,
                "keepLastAmount": 14
              }
            },
            "logging": {
              "enabled": true,
              "level": "log"
            },
            "newVersionCheck": {
              "enabled": true
            },
            "notifications": {
              "smtp": {
                "enabled": false,
                "from": "",
                "replyTo": "",
                "transport": {
                  "host": "",
                  "ignoreCert": false,
                  "password": "",
                  "port": 587,
                  "secure": false,
                  "username": ""
                }
              }
            },
            "oauth": {
              "enabled": true,
              "autoRegister": true,
              "clientId": "immich",
              "clientSecret": "{{ .OAUTH_CLIENT_SECRET }}",
              "issuerUrl": "https://auth.${SECRET_DOMAIN}"
            },
            "passwordLogin": {
              "enabled": false
            },
            "server": {
              "externalDomain": "https://photos.${SECRET_DOMAIN}"
            },
            "trash": {
              "days": 30,
              "enabled": true
            },
            "user": {
              "deleteDelay": 7
            }
          }
  data:
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: authelia
        property: IMMICH_OAUTH_CLIENT_SECRET
