---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nut-relay-config
data:
  nut.conf: |
    MODE=netserver
  ups.conf: |
    [ups]
      driver = dummy-ups
      port = ups@${SECRET_NAS_IP}
      desc = "Synology UPS relay"
      repeater_disable_strict_start = true
  upsd.conf: |
    LISTEN 0.0.0.0 3493
  upsd.users: |
    [monuser]
      password = nutrelay
      upsmon secondary
