---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-relay
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nut-relay-secret
    creationPolicy: Owner
  data:
    - secretKey: API_PASSWORD
      remoteRef:
        key: nut-relay
        property: password
