---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: blocky-configmap
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
