---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claude-notify-personal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: claude-notify-personal-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: claude-notify-personal
