---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/external-secrets/external-secrets/app
  dependsOn:
    - name: external-secrets-operator
    - name: onepassword-connect
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  interval: 30m
