apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cluster-config-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: cluster-config
        property: DOMAIN
    - secretKey: SECRET_PUBLIC_DOMAIN
      remoteRef:
        key: cluster-config
        property: PUBLIC_DOMAIN
    - secretKey: SECRET_CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: cloudflare-tunnel
        property: CLOUDFLARE_TUNNEL_ID
    - secretKey: SECRET_CLOUDFLARE_EMAIL
      remoteRef:
        key: cloudflare-dns
        property: CLOUDFLARE_EMAIL
