---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-repos
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/flux/repositories/private/repos
  prune: true
  dependsOn:
    - name: external-secrets
  sourceRef:
    kind: GitRepository
    name: homelab
