---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/apps
  prune: true
  dependsOn:
    - name: cluster-config-secret
  sourceRef:
    kind: GitRepository
    name: homelab
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-config-secret
