---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gateway
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/network/gateway/app
  dependsOn:
    - name: envoy-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  interval: 30m
