---
apiVersion: v1
kind: Service
metadata:
  name: postgres17-lb
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres17
    role: primary
