---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./service.yaml
  - ./statefulset.yaml
  - ../../../../templates/volsync
generatorOptions:
  disableNameSuffixHash: true
