---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app onepassword-connect
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/external-secrets/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  interval: 30m
