---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rtlamr2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      tolerations:
        - key: "homelab/special-node"
          operator: "Equal"
          value: "laundry-pi"
          effect: "NoSchedule"
    controllers:
      rtlamr2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/allangood/rtlamr2mqtt
              tag: 2025.6.6@sha256:9458419acca5f95d438b3a04f10291d19c37244e16c0286ee2033eb4465ad0a0
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
        pod:
          nodeSelector:
            rtlamr.feature.node.kubernetes.io/rtlamr: "true"
    persistence:
      config-file:
        type: secret
        name: rtlamr2mqtt-secret
        globalMounts:
          - path: /etc/rtlamr2mqtt.yaml
            subPath: rtlamr2mqtt.yaml
            readOnly: true
