---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster-config-secret
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/external-secrets/cluster-config-secret/app
  dependsOn:
    - name: external-secrets-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  interval: 30m
