---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./route.yaml
  - ./service.yaml
  - ./statefulset.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: zigbee2mqtt-configmap
    files:
      - configuration.yaml=./config/zigbee2mqtt.yaml
  - name: zigbee2mqtt-cleanup-script
    files:
      - cleanup-devices.py=./config/cleanup-devices.py
generatorOptions:
  disableNameSuffixHash: true
