---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hass-secret-configs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hass-secret-configs
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          homeassistant_latitude: {{ .LATITUDE }}
          homeassistant_longitude: {{ .LONGITUDE }}
          homeassistant_elevation: {{ .ELEVATION }}
          recorder_db_url: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres17-rw.database.svc.cluster.local/homeassistant
          ecobee_api_key: {{ .ECOBEE_API_KEY }}
  dataFrom:
    - extract:
        key: homeassistant-secrets
