apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  interval: 20m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  values:
    config:
      envoyGateway:
        logging:
          level:
            default: debug
