apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kube-web-view
spec:
  hostnames:
    - "kube-web-view.internal.${SECRET_DOMAIN}"
  parentRefs:
    - name: internal
      namespace: network
  rules:
    - backendRefs:
        - kind: Service
          name: kube-web-view
          port: 80
