---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "hass-static-configs"
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "ceph-filesystem"
