apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deploy-key-hass-configs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: deploy-key-hass-configs
    creationPolicy: Owner
  data:
    - secretKey: identity
      remoteRef:
        key: deploy_key_hass_configs
        property: identity
    - secretKey: known_hosts
      remoteRef:
        key: deploy_key_hass_configs
        property: known_hosts
