---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-web-view
  namespace: flux-system
spec:
  targetNamespace: kube-web-view
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/cluster-util/kube-web-view/app
  dependsOn:
    - name: gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  interval: 30m
