apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
spec:
  interval: 1m
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: 1password-connect
        namespace: flux-system
  values:
    connect:
      credentialsName: onepassword-connect-credentials
      serviceType: ClusterIP
